import { useEffect, useState } from 'react'
import electron from '../lib/electron'
import { isTauriRuntime } from '../lib/tauri-native-bridge'

type State = { mode: 'observe' | 'draft' | 'auto'; responsePermission: boolean; paused: boolean; emergencyPaused: boolean; recoveryMode?: boolean; status: string; queueDepth: number; activeJob: string | null; lastProcessedMessage: string | null; lastError: string | null; escalations: number; lastDeliveryStatus: string | null; lastProviderMessageId: string | null; lastDeliveryInboundId: string | null; usageToday?: { llmCalls: number; outboundMessages: number; estimatedCost: number } }

const initial: State = { mode: 'observe', responsePermission: false, paused: true, emergencyPaused: false, recoveryMode: false, status: 'stopped', queueDepth: 0, activeJob: null, lastProcessedMessage: null, lastError: null, escalations: 0, lastDeliveryStatus: null, lastProviderMessageId: null, lastDeliveryInboundId: null, usageToday: { llmCalls: 0, outboundMessages: 0, estimatedCost: 0 } }

export function AutonomyPanel() {
  const browserRuntime = typeof window !== 'undefined' && !window.electron && !isTauriRuntime()
  const [state, setState] = useState<State>(initial)
  const [drafts, setDrafts] = useState<Array<{ inboundId: string; jid: string; content: string; contentHash: string; expiresAt: number; status?: string; providerMessageId?: string; sendStatus?: string; sendError?: string }>>([])
  const [templates, setTemplates] = useState<Array<{ name: string; languageCode: string }>>([])
  const [takeovers, setTakeovers] = useState<Array<{ jid: string; source: string; startedAt: number }>>([])
  const [health, setHealth] = useState<{ executionLocation?: string; transport?: string; baileysExperimentalApproval?: boolean; llmConfigured?: boolean; llm?: { provider: string; model: string; configured: boolean }; llmDataPolicyApproved?: boolean; channel?: { status: string; error: string | null; phoneNumber?: string | null }; browser?: { status: string; error: string | null; lastHealthCheck: number }; extension?: { status: string; port: number; lastStatus: string | null; error: string | null }; email?: { status: string; error: string | null }; network?: { status: string; latencyMs?: number; error?: string }; providers?: { meta?: { configured: boolean }; x?: { configured: boolean } }; queues?: { whatsapp: number; email: number; meta: number }; rag?: { status: string; documents: number }; memory?: { status: string; backend: string | null }; escalation?: { contact: string | null; contactConfigured: boolean; slaMinutes: number; overdue?: number }; memoryRss?: number; leaseHeld?: boolean } | null>(null)
  const [metrics, setMetrics] = useState<{ inbound: number; sent: number; escalated: number; drafts: number; failed: number; averageDecisionLatencyMs: number; llmCalls?: number; averageLlmLatencyMs?: number; groundedDecisionRate: number; deliveryUnknown: number; draftApprovalRate: number; averageDraftEditingTimeMs: number; estimatedCostPerResolvedConversation: number; reviewedDecisions: number; reviewAccuracy: number; escalationPrecision: number; unnecessaryEscalations: number; missedEscalations: number; recoveryDrills: number; averageRecoveryTimeMs: number } | null>(null)
  const [templateChoice, setTemplateChoice] = useState<Record<string, string>>({})
  const [notifications, setNotifications] = useState<Array<{ id: number; kind: string; details: string }>>([])
  const [unresolved, setUnresolved] = useState<Array<{ inboundId: string; jid: string; content: string; providerMessageId: string | null; sentAt: number; status: string; error: string | null }>>([])
  const [deliveryHistory, setDeliveryHistory] = useState<Array<{ providerMessageId: string; channel: string; status: string; eventAt: number; inboundId: string | null }>>([])
  const [emailAttachments, setEmailAttachments] = useState<Array<{ inboundId: string; messageId: string; id: string; name?: string; mimeType?: string; size?: number; receivedAt: number }>>([])
  const [attachmentScans, setAttachmentScans] = useState<Record<string, { safe: boolean; reason: string; size: number; sha256: string; detectedType: string }>>({})
  const [attachmentError, setAttachmentError] = useState<string | null>(null)
  const [decisionEvidence, setDecisionEvidence] = useState<Array<{ inboundId: string; jid: string; createdAt: number; decision: { grounding: string; reason: string; evidence?: Array<{ fileName: string; filePath: string; rank?: number }> } }>>([])
  const [usageHistory, setUsageHistory] = useState<Array<{ day: string; llmCalls: number; outboundMessages: number; estimatedCost: number }>>([])
  const [channelUsage, setChannelUsage] = useState<Array<{ channel: string; amount: number }>>([])
  const [webState, setWebState] = useState<{ status: string; error?: string | null; profile?: string } | null>(null)
  const [webChatId, setWebChatId] = useState('')
  const refreshDrafts = () => electron.autonomy.listDrafts().then(setDrafts).catch(() => setDrafts([]))
  const refreshTemplates = () => electron.autonomy.listApprovedTemplates().then(setTemplates).catch(() => setTemplates([]))
  const refreshTakeovers = () => electron.autonomy.listTakeovers().then(setTakeovers).catch(() => setTakeovers([]))
  const refreshNotifications = () => electron.autonomy.listNotifications().then(setNotifications).catch(() => setNotifications([]))
  const refreshUnresolved = () => electron.autonomy.listUnresolvedOutbound().then(setUnresolved).catch(() => setUnresolved([]))
  const refreshDeliveryHistory = () => electron.autonomy.listDeliveryHistory(20).then(setDeliveryHistory).catch(() => setDeliveryHistory([]))
  const refreshEmailAttachments = () => electron.autonomy.listEmailAttachments(20).then((items: Array<{ inboundId: string; messageId: string; name?: string; mimeType?: string; size?: number; receivedAt: number; id?: string }>) => setEmailAttachments(items.map(item => ({ ...item, id: item.id || '' })).filter(item => item.id))).catch(() => setEmailAttachments([]))
  const refreshDecisionEvidence = () => electron.autonomy.listDecisionEvidence(20).then(setDecisionEvidence).catch(() => setDecisionEvidence([]))
  const refreshUsage = () => { electron.autonomy.usageHistory(14).then(setUsageHistory).catch(() => setUsageHistory([])); electron.autonomy.channelUsage(1).then(setChannelUsage).catch(() => setChannelUsage([])) }
  useEffect(() => {
    electron.autonomy.getState().then(setState)
    electron.autonomy.getHealth().then(setHealth)
    electron.autonomy.getMetrics(14).then(setMetrics)
    if (!browserRuntime) electron.whatsapp.web.getState().then(setWebState)
    refreshDrafts(); refreshTemplates(); refreshTakeovers(); refreshNotifications(); refreshUnresolved(); refreshDeliveryHistory(); refreshEmailAttachments(); refreshDecisionEvidence(); refreshUsage()
    const unsub = electron.autonomy.onState((s) => {
      setState(s as State)
      electron.autonomy.getHealth().then(setHealth)
      electron.autonomy.getMetrics(14).then(setMetrics)
      if (!browserRuntime) electron.whatsapp.web.getState().then(setWebState)
      refreshDrafts(); refreshTemplates(); refreshTakeovers(); refreshNotifications(); refreshUnresolved(); refreshDeliveryHistory(); refreshEmailAttachments(); refreshDecisionEvidence(); refreshUsage()
    })
    const unsubNotification = electron.autonomy.onNotification(() => { refreshNotifications(); refreshUnresolved(); refreshDeliveryHistory(); refreshEmailAttachments(); refreshDecisionEvidence() })
    return () => { unsub(); unsubNotification() }
  }, [browserRuntime])
  const inspectAttachment = async (attachment: typeof emailAttachments[number]) => {
    setAttachmentError(null)
    try {
      const result = await electron.autonomy.retrieveGmailAttachment(attachment.messageId, attachment.id, { mimeType: attachment.mimeType, name: attachment.name })
      if (!result?.scan) { setAttachmentError('Attachment inspection returned no scan result.'); return }
      setAttachmentScans({ ...attachmentScans, [attachment.inboundId + ':' + attachment.id]: result.scan })
      if (result.scan.safe && result.bytes) { const url = URL.createObjectURL(new Blob([result.bytes], { type: attachment.mimeType || 'application/octet-stream' })); const link = document.createElement('a'); link.href = url; link.download = attachment.name || 'email-attachment'; link.click(); URL.revokeObjectURL(url) }
    } catch {
      setAttachmentError('Attachment inspection failed. Review the owner audit log for details.')
    }
  }
  const updateMode = (mode: State['mode']) => electron.autonomy.setMode(mode, mode === 'auto' ? state.responsePermission : false).then(setState)
  return <div className="bg-[var(--color-card-elevated)] border border-[var(--color-border)] rounded-xl p-6 space-y-4">
    <div className="flex items-center justify-between"><div><h4 className="font-bold">Autonomous Supervisor</h4><p className="text-xs text-[var(--color-text-muted)]">{browserRuntime ? 'agentd-backed, draft-only controls' : 'Main-process, durable, auditable controls'}</p></div><span className="text-xs px-2 py-1 rounded bg-white/10">{state.status}</span></div>
    {state.recoveryMode && <div className="rounded-lg bg-orange-500/15 p-2 text-xs text-orange-200">Recovery hold active. Restart to apply a staged backup, verify restored data, then clear the hold before resuming. <button onClick={() => electron.autonomy.clearRecoveryMode().then(setState)} className="underline">Clear hold</button></div>}
    {!browserRuntime && <button onClick={async () => { const file = await electron.app.selectFile({ title: 'Select autonomy backup', filters: [{ name: 'SQLite backup', extensions: ['db'] }] }); if (file) electron.autonomy.stageBackup(file).then(setState) }} className="px-3 py-2 rounded-lg bg-white/10 text-xs">Stage backup for restore</button>}
    <div className="grid grid-cols-3 gap-2">{(['observe', 'draft', 'auto'] as const).map(mode => <button key={mode} disabled={browserRuntime && mode === 'auto'} onClick={() => updateMode(mode)} className={`rounded-lg px-3 py-2 text-xs ${state.mode === mode ? 'bg-[#25D366] text-white' : 'bg-white/5 text-gray-300'} disabled:cursor-not-allowed disabled:opacity-40`}>{mode === 'observe' ? 'Observe only' : mode === 'draft' ? 'Draft mode' : browserRuntime ? 'Auto-reply unavailable' : 'Auto-reply'}</button>)}</div>
    <button onClick={() => electron.autonomy.setMode(state.mode, !state.responsePermission).then(setState)} className={`w-full rounded-lg px-3 py-2 text-left text-xs ${state.responsePermission ? 'bg-green-500/15 text-green-200' : 'bg-white/5 text-gray-300'}`}>Response permission: {state.responsePermission ? 'On' : 'Off'} <span className="float-right">{state.mode === 'auto' ? 'independent host send gate' : 'auto-reply mode required'}</span></button>
    <div className="grid grid-cols-2 gap-2 text-xs text-[var(--color-text-muted)]"><span>Queue: {state.queueDepth}</span><span>Escalations: {state.escalations}</span><span>Permission: {state.responsePermission ? 'on' : 'off'}</span><span>Job: {state.activeJob || 'idle'}</span><span>Last processed: {state.lastProcessedMessage || 'none'}</span><span>Delivery: {state.lastDeliveryStatus || 'none'}</span><span>Provider ID: {state.lastProviderMessageId || 'none'}</span><span>LLM today: {state.usageToday?.llmCalls ?? 0}</span><span>Replies today: {state.usageToday?.outboundMessages ?? 0}</span><span>Estimated cost: {state.usageToday?.estimatedCost?.toFixed(4) ?? '0.0000'}</span></div>
    {health && <div className="rounded-lg bg-white/5 p-2 text-xs text-[var(--color-text-muted)]"><p>Execution: {health.executionLocation || 'unknown'} · Transport: {health.transport || 'unknown'} · LLM: {health.llm?.provider || 'unknown'} / {health.llm?.model || 'unknown'} ({health.llm?.configured ?? health.llmConfigured ? 'configured' : 'not configured'}) · Data approval: {health.llmDataPolicyApproved ? 'approved' : 'required'} · Baileys Auto-reply: {health.baileysExperimentalApproval ? 'approved' : 'blocked'}</p><p>WhatsApp: {health.channel?.status}{health.channel?.error ? ` · ${health.channel.error}` : ''} · Browser: {health.browser?.status ?? 'unknown'} · Extension: {health.extension?.status ?? 'disabled'} · Network: {health.network?.status ?? 'unknown'}{health.network?.latencyMs !== undefined ? ` (${health.network.latencyMs} ms)` : ''} · Meta: {health.providers?.meta?.configured ? 'configured' : 'not configured'} · X: {health.providers?.x?.configured ? 'configured' : 'not configured'}</p><p>Email: {health.email?.status ?? 'unknown'}{health.email?.error ? ` · ${health.email.error}` : ''}</p><p>Queues: WhatsApp {health.queues?.whatsapp ?? 0} · Email {health.queues?.email ?? 0} · Meta/X {health.queues?.meta ?? 0}</p><p>RAG: {health.rag?.status ?? 'unknown'} · Documents: {health.rag?.documents ?? 0} · Memory backend: {health.memory?.backend || health.memory?.status || 'unknown'}</p><p>Escalation: {health.escalation?.contactConfigured ? health.escalation.contact : 'contact not configured'} · SLA: {health.escalation?.slaMinutes ?? 60} min · Overdue: {health.escalation?.overdue ?? 0}</p><p>Lease: {health.leaseHeld ? 'held' : 'not held'} · Memory: {health.memoryRss ? `${Math.round(health.memoryRss / 1024 / 1024)} MB` : 'unknown'}</p>{!browserRuntime && <button onClick={() => electron.autonomy.reconnectChannel().then(setState).then(() => electron.autonomy.getHealth().then(setHealth))} className="mt-2 px-2 py-1 rounded bg-white/10">Reconnect WhatsApp</button>}</div>}
    {!browserRuntime && webState && <div className="rounded-lg bg-white/5 p-2 text-xs text-[var(--color-text-muted)]"><p>WhatsApp Web: {webState.status}{webState.error ? ` · ${webState.error}` : ''}</p><p>Profile: {webState.profile || 'dedicated persistent profile'}</p><div className="mt-2 flex flex-wrap gap-2"><button onClick={() => electron.whatsapp.web.start().then(setWebState)} className="px-2 py-1 rounded bg-white/10">Open Web</button><input value={webChatId} onChange={event => setWebChatId(event.target.value)} placeholder="Chat ID" className="rounded bg-black/20 px-2 py-1" /><button disabled={!webChatId.trim()} onClick={() => electron.whatsapp.web.startMonitoring(webChatId.trim()).then(setWebState)} className="px-2 py-1 rounded bg-blue-500/20 text-blue-200 disabled:opacity-40">Monitor chat</button><button onClick={() => electron.whatsapp.web.stopMonitoring()} className="px-2 py-1 rounded bg-white/10">Stop monitor</button><button onClick={() => electron.whatsapp.web.humanTakeover().then(setWebState)} className="px-2 py-1 rounded bg-orange-500/20 text-orange-200">Human takeover</button><button onClick={() => electron.whatsapp.web.captureFailure().then(path => path && setWebState({ ...webState, error: `Screenshot: ${path}` }))} className="px-2 py-1 rounded bg-white/10">Capture failure</button></div></div>}
    {metrics && <div className="rounded-lg bg-white/5 p-2 text-xs text-[var(--color-text-muted)]"><p className="font-semibold">Pilot metrics · 14 days</p><p>Inbound: {metrics.inbound} · Sent: {metrics.sent} · Escalated: {metrics.escalated}</p><p>Drafts: {metrics.drafts} · Failed: {metrics.failed} · Avg decision: {Math.round(metrics.averageDecisionLatencyMs)} ms</p><p>LLM calls: {metrics.llmCalls ?? 0} · Avg LLM latency: {Math.round(metrics.averageLlmLatencyMs ?? 0)} ms</p><p>Grounded: {(metrics.groundedDecisionRate * 100).toFixed(1)}% · Delivery unknown: {metrics.deliveryUnknown}</p><p>Draft approval: {(metrics.draftApprovalRate * 100).toFixed(1)}% · Avg edit: {Math.round(metrics.averageDraftEditingTimeMs)} ms · Cost/resolved: {metrics.estimatedCostPerResolvedConversation.toFixed(4)}</p><p>Reviewed: {metrics.reviewedDecisions} · Accuracy: {(metrics.reviewAccuracy * 100).toFixed(1)}% · Escalation precision: {(metrics.escalationPrecision * 100).toFixed(1)}%</p><p>Unnecessary escalations: {metrics.unnecessaryEscalations} · Missed escalations: {metrics.missedEscalations}</p><p>Recovery drills: {metrics.recoveryDrills} · Avg recovery: {Math.round(metrics.averageRecoveryTimeMs)} ms</p></div>}
    {state.lastDeliveryStatus === 'delivery-unknown' && state.lastDeliveryInboundId && <div className="flex gap-2"><button onClick={() => electron.autonomy.retryDelivery(state.lastDeliveryInboundId).then(setState)} className="px-3 py-2 rounded-lg bg-yellow-500/20 text-yellow-200 text-xs">Retry delivery</button><button onClick={() => electron.autonomy.quarantineDelivery(state.lastDeliveryInboundId).then(setState)} className="px-3 py-2 rounded-lg bg-white/10 text-xs">Quarantine</button></div>}
    {unresolved.length > 0 && <div className="space-y-2"><p className="text-xs font-semibold text-yellow-200">Unresolved outbound</p>{unresolved.map(item => <div key={item.inboundId} className="rounded-lg bg-yellow-500/10 p-2 text-xs"><p>{item.status} · {item.jid} · {item.providerMessageId || 'no provider ID'}</p><p className="text-[10px] text-gray-400">{item.content.slice(0, 160)}{item.content.length > 160 ? '…' : ''}{item.error ? ` · ${item.error}` : ''}</p>{item.status === 'delivery-unknown' && <div className="mt-1 flex gap-2"><button onClick={() => electron.autonomy.retryDelivery(item.inboundId).then(setState).then(refreshUnresolved)} className="px-2 py-1 rounded bg-yellow-500/20 text-yellow-100">Retry</button><button onClick={() => electron.autonomy.quarantineDelivery(item.inboundId).then(setState).then(refreshUnresolved)} className="px-2 py-1 rounded bg-white/10">Quarantine</button></div>}</div>)}</div>}
    {deliveryHistory.length > 0 && <details className="rounded-lg bg-white/5 p-2 text-xs text-[var(--color-text-muted)]"><summary className="cursor-pointer font-semibold">Delivery history</summary><div className="mt-2 space-y-1">{deliveryHistory.map((event, index) => <p key={`${event.providerMessageId}-${event.eventAt}-${index}`}>{event.channel} · {event.status} · {event.providerMessageId} · {new Date(event.eventAt).toLocaleString()}</p>)}</div></details>}
    {emailAttachments.length > 0 && <details className="rounded-lg bg-white/5 p-2 text-xs text-[var(--color-text-muted)]"><summary className="cursor-pointer font-semibold">Email attachments · operator inspection</summary><p className="mt-1 text-[10px]">Attachments are never sent to the autonomous agent. Inspection downloads only content that passes bounded size and type checks; this is not antivirus scanning.</p>{attachmentError && <p className="mt-1 text-red-300">{attachmentError}</p>}<div className="mt-2 space-y-2">{emailAttachments.map(attachment => { const key = `${attachment.inboundId}:${attachment.id}`; const scan = attachmentScans[key]; return <div key={key} className="rounded bg-black/10 p-2"><p>{attachment.name || 'unnamed'} · {attachment.mimeType || 'unknown MIME'} · {attachment.size ?? '?'} bytes</p><button onClick={() => inspectAttachment(attachment)} className="mt-1 rounded bg-white/10 px-2 py-1">Inspect attachment</button>{scan && <p className={scan.safe ? 'text-green-200' : 'text-red-300'}>{scan.safe ? `Passed bounded checks (${scan.detectedType})` : `Rejected: ${scan.reason}`} · SHA-256 {scan.sha256}</p>}</div> })}</div></details>}
    {decisionEvidence.length > 0 && <details className="rounded-lg bg-white/5 p-2 text-xs text-[var(--color-text-muted)]"><summary className="cursor-pointer font-semibold">Decision evidence and review</summary><div className="mt-2 space-y-2">{decisionEvidence.map(item => <div key={item.inboundId}><p>{item.jid} · {item.decision.grounding} · {item.decision.reason}</p><p className="text-[10px] text-gray-400">{item.decision.evidence?.map(source => source.fileName).join(', ') || 'No source evidence recorded'}</p><div className="mt-1 flex flex-wrap gap-1">{(['correct', 'incorrect', 'unnecessary_escalation', 'missed_escalation'] as const).map(label => <button key={label} onClick={() => electron.autonomy.reviewDecision(item.inboundId, label).then(() => electron.autonomy.getMetrics(14).then(setMetrics))} className="rounded bg-white/10 px-2 py-1 text-[10px]">{label.replaceAll('_', ' ')}</button>)}</div></div>)}</div></details>}
    {drafts.length > 0 && <div className="space-y-2"><p className="text-xs font-semibold">Pending drafts</p>{drafts.map(draft => { const selected = templateChoice[draft.inboundId] || ''; const [name, languageCode] = selected.split('|'); const approved = draft.status === 'approved'; return <div key={draft.inboundId} className="rounded-lg bg-white/5 p-2 text-xs"><p className="text-gray-300">{draft.jid}: {draft.content}</p><p className="mt-1 text-[10px] text-gray-500">Hash: {draft.contentHash} · Expires: {new Date(draft.expiresAt).toLocaleString()} · Status: {draft.status || 'draft'}{draft.sendStatus ? ` · Send: ${draft.sendStatus}` : ''}</p>{draft.sendError && <p className="mt-1 text-[10px] text-red-300">{draft.sendError}</p>}<div className="mt-2 flex flex-wrap gap-2">{approved && browserRuntime && draft.sendStatus === 'failed' && draft.sendError !== 'Quarantined by operator' && draft.sendError !== 'Cancelled by operator' ? <><button onClick={() => electron.autonomy.retryDelivery(draft.inboundId).then(setState).then(refreshDrafts)} className="px-2 py-1 rounded bg-yellow-500/20 text-yellow-100">Retry</button><button onClick={() => electron.autonomy.quarantineDelivery(draft.inboundId).then(setState).then(refreshDrafts)} className="px-2 py-1 rounded bg-white/10">Quarantine</button><button onClick={() => electron.autonomy.cancelOutbound(draft.inboundId).then(setState).then(refreshDrafts)} className="px-2 py-1 rounded bg-white/10">Cancel</button></> : approved && browserRuntime ? <button onClick={() => electron.autonomy.sendApprovedDraft(draft.inboundId).then(setState).then(refreshDrafts)} className="px-2 py-1 rounded bg-[#25D366] text-white">Send approved draft</button> : <button onClick={() => electron.autonomy.approveDraft(draft.inboundId).then(setState).then(refreshDrafts)} className="px-2 py-1 rounded bg-[#25D366] text-white">{browserRuntime ? 'Approve draft' : 'Approve and send'}</button>}{templates.length > 0 && <><select value={selected} onChange={event => setTemplateChoice({ ...templateChoice, [draft.inboundId]: event.target.value })} className="rounded bg-black/20 px-2 py-1"><option value="">Template…</option>{templates.map(template => <option key={`${template.name}|${template.languageCode}`} value={`${template.name}|${template.languageCode}`}>{template.name} ({template.languageCode})</option>)}</select><button disabled={!name} onClick={() => electron.autonomy.sendApprovedTemplate(draft.inboundId, name, languageCode).then(setState).then(refreshDrafts)} className="px-2 py-1 rounded bg-blue-500/20 text-blue-200 disabled:opacity-40">Send template</button></>}</div></div> })}</div>}
    {takeovers.length > 0 && <div className="space-y-2"><p className="text-xs font-semibold text-orange-200">Human takeovers</p>{takeovers.map(takeover => <div key={takeover.jid} className="flex items-center justify-between rounded-lg bg-orange-500/10 p-2 text-xs"><span>{takeover.jid} · {takeover.source} · {new Date(takeover.startedAt).toLocaleString()}</span><button onClick={() => electron.autonomy.resumeConversation(takeover.jid).then(setState).then(refreshTakeovers)} className="ml-2 px-2 py-1 rounded bg-white/10">Resume bot</button></div>)}</div>}
    {notifications.length > 0 && <div className="space-y-2"><p className="text-xs font-semibold text-yellow-200">Owner notifications</p>{notifications.slice(0, 5).map(note => <button key={note.id} onClick={() => electron.autonomy.ackNotification(note.id).then(refreshNotifications)} className="block w-full rounded-lg bg-yellow-500/10 p-2 text-left text-xs text-yellow-100">{note.kind}: {note.details}</button>)}</div>}
    {usageHistory.length > 0 && <div className="space-y-1 text-xs text-[var(--color-text-muted)]"><p className="font-semibold">Usage history</p>{usageHistory.slice(0, 7).map(day => <p key={day.day}>{day.day}: {day.llmCalls} LLM, {day.outboundMessages} replies, {day.estimatedCost.toFixed(4)} estimated cost</p>)}</div>}
    {channelUsage.length > 0 && <div className="space-y-1 text-xs text-[var(--color-text-muted)]"><p className="font-semibold">Outbound by channel · today</p>{channelUsage.map(item => <p key={item.channel}>{item.channel}: {item.amount}</p>)}</div>}
    {!browserRuntime && <button onClick={() => electron.autonomy.pruneRetention().then(setState)} className="px-3 py-2 rounded-lg bg-white/10 text-xs">Prune expired local data</button>}
    {state.lastError && <p className="text-xs text-red-400">{state.lastError}</p>}
    <div className="flex gap-2"><button onClick={() => (state.paused ? electron.autonomy.resume() : electron.autonomy.pause()).then(setState)} className="px-3 py-2 rounded-lg bg-white/10 text-xs">{state.paused ? 'Resume' : 'Pause'}</button><button onClick={() => electron.autonomy.pause(true).then(setState)} className="px-3 py-2 rounded-lg bg-red-500/20 text-red-300 text-xs">Pause All</button><button onClick={() => electron.autonomy.start().then(setState)} className="px-3 py-2 rounded-lg bg-white/10 text-xs">Start</button></div>
  </div>
}
